### ISSUE TITLE
What if the controller calcuates a steering angle that we cannot acheive? We might have to go back to 90 degree from time to time to know where the servo is.

### ISSUE THREAD

**Issue by hugocool24** [hugocool24/RobotSM#1]
https://github.com/hugocool24/RobotSM/blob/772e233bbb1975d9b4a02c7206f58512880499c3/2018/main.ino#L127

**Comment by michelco86** [comment]
if (u[1] > deltamax) {
    u[1] = deltamax;
  }

  if (u[1] < -deltamax) {
    u[1] = -deltamax;
  }

this code in the controller function limits the upper and lower angle of the computed steering angle. this is then mapped by:

u[1] = map(u[1],-deltamax,deltamax,180-15,15);

to get the proper range for the steering servo (0->180)

**Comment by michelco86** [comment]
We should double check the mapping. I'm not sure if it should be map(blabla,180,0) or map(blabla,0,180)
