### ISSUE TITLE
We feed the steering with angles 0, -45, -45 when we should feed it with 0, 135, 45

### ISSUE THREAD

**Issue by hugocool24** [hugocool24/RobotSM#2]
https://github.com/hugocool24/RobotSM/blob/772e233bbb1975d9b4a02c7206f58512880499c3/2018/main.ino#L179

**Comment by michelco86** [comment]
Alpha is the angle of the point we will aim at. The point is defined by distance d and angle alpha relative to the car. This angle alpha is then sent to the control algorithm which computes the actual steering angle which is then sent to the steering servo
